name: Release

on:
  push:
    tags: ["*"]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version-file: .java-version
          distribution: temurin
      - name: Build
        run: ./gradlew --no-daemon assembleLocal
      - name: Create Release
        run: gh release create --draft --title "$GITHUB_REF_NAME" "$GITHUB_REF_NAME" app/build/outputs/apk/local/app-*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
